# Check if someone is a teenager (13–19)
age = int(input("Enter your age: "))
if age >= 13 and age <= 19:
    print("You are a teenager.")
else:
    print("You are not a teenager.\
          \nyou are a big boy or girl.\
          \nor you are a kid.\
          \ngo and study or earn.")
# Ignore the nonesense part and continue with the rest of the code.
# Its just a way self enjoyment to get a bit creative with the code.
