a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Quotient:", a / b)
print("Remainder:", a % b)
print("Exponentiation:", a ** b)
# compare  the a and b
print(f"Comparison: {a} is equal to {b}: {a == b}")
print(f"Comparison: {a} is not equal to {b}: {a != b}")
print(f"Comparison: {a} is greater than {b}: {a > b}")
print(f"Comparison: {a} is less than {b}: {a < b}")
print(f"Comparison: {a} is greater than or equal to {b}: {a >= b}")
print(f"Comparison: {a} is less than or equal to {b}: {a <= b}")
